server:
  port: 8003
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  servlet:
    multipart:
      #最大上传单个文件大小：默认1M
      max-file-size: 1024MB
      #最大总上传数据大小：默认1M
      max-request-size: 1024MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

aliyun:
  vod:
    file:
      keyid: 
      keysecret: 
