# 服务端口
server:
  port: 8004
# 服务名
spring:
  application:
    name: service-cms
# mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/langju_online?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
# 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/zzl/educms/mapper/xml/*.xml
# mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
